---
- name: "Install zsh"
  apt: name="zsh" update_cache=yes cache_valid_time=3600 state=latest
  become: yes

- name: Use zsh as default shell
  user: name={{ item.user | default(item) }} shell=/bin/zsh
  become: yes
  when: item.default_shell | default(True)
  with_items: "{{ zsh_users }}"

- name: Use zsh as default shell for new user
  lineinfile: dest=/etc/adduser.conf regexp="^DSHELL=" line="DSHELL=/bin/zsh"
  become: yes
  when: zsh_default_shell_for_new_user

- name: copy user zshrc
  copy: src={{ item.zsh_rc_file_source_path }} dest="~/.zshrc"
  become: yes
  become_user: "{{ item.user }}"
  when: item.zsh_rc_file_source_path is defined
  with_items: "{{ zsh_users }}"

- name: copy global zshrc
  become: yes
  copy: src={{ zsh_global_rc_file_source_path }} dest={{ zsh_global_rc_file_path }} owner=root group=root mode=0644
  when: zsh_global_rc_file_source_path is defined
